// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package logic

import (
	_ "gitee.com/thorxh/thor-api/internal/logic/phrase"
)
