// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// Phrase is the golang structure of table phrase for DAO operations like Where/Data.
type Phrase struct {
	g.Meta     `orm:"table:phrase, do:true"`
	Id         interface{} // 自增主键
	Phrase     interface{} // 成语
	Pinyin     interface{} // 拼音
	Explain    interface{} // 解释
	CreateTime *gtime.Time // 数据创建时间
	ModifyTime *gtime.Time // 数据更新时间
}
