// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package service

import (
	"context"
	"server/internal/model"
)

type IPhrase interface {
	Query(ctx context.Context, in model.PhraseQueryInput) (err error)
}

var localPhrase IPhrase

func Phrase() IPhrase {
	if localPhrase == nil {
		panic("implement not found for interface IPhrase, forgot register?")
	}
	return localPhrase
}

func RegisterPhrase(i IPhrase) {
	localPhrase = i
}
