// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package service

import (
	"context"
)

type IPhrase interface {
	Query(ctx context.Context) (err error)
}

var localPhrase IPhrase

func Phrase() IPhrase {
	if localPhrase == nil {
		panic("implement not found for interface IPhrase, forgot register?")
	}
	return localPhrase
}

func RegisterUser(i IPhrase) {
	localPhrase = i
}
