// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gitee.com/thorxh/thor-api/internal/dao/internal"
)

// internalPhraseDao is internal type for wrapping internal DAO implements.
type internalPhraseDao = *internal.PhraseDao

// phraseDao is the data access object for table phrase.
// You can define custom methods on it to extend its functionality as you wish.
type phraseDao struct {
	internalPhraseDao
}

var (
	// Phrase is globally public accessible object for table phrase operations.
	Phrase = phraseDao{
		internal.NewPhraseDao(),
	}
)

// Fill with you ideas below.
