// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// Phrase is the golang structure for table phrase.
type Phrase struct {
	Id         int         `json:"id"         ` // 自增主键
	Phrase     string      `json:"phrase"     ` // 成语
	Pinyin     string      `json:"pinyin"     ` // 拼音
	Explain    string      `json:"explain"    ` // 解释
	CreateTime *gtime.Time `json:"createTime" ` // 数据创建时间
	ModifyTime *gtime.Time `json:"modifyTime" ` // 数据更新时间
}
